### ISSUE TITLE
Paideia Website: Discussions Integration

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/paideia#4]
## Goal
Have `paideia.im` website support web 2.0 interactions for discussions etc.
### Tasks Breakdown
- [x] Have backend deployed
- [x] Integration for auth and login
- [x] Allow users to create and participate in discussions on the website

### Additional API notes
- [x] have reference metadata returned with proposals instead of just ids
- [x] make user details and settings (xp, level) etc dao specific
- [x] search users by wallet address (auto complete endpoint)
- [x] make token_holders optional for dao creation (not a required field)
- [x] get daos by name (helps fetch data from dao url)
- [x] add token id to tokenomics table table
- [x] add status column for proposals table
- [x] comments websockets - should return only the last one
- [x] likes and dislikes for comments

### User Details and User Id
fk constraint for the following should be `user_details(id)` i.e. users should have scope per dao
- Followers
- Comments
- Likes/Dislikes
- Proposals
- Activities
- Notifications

**Progess**
- [x] Impl
- [x] Testing
- [x] Review

### Blockers
- waiting on ErgoAuth
- currently using beta versions (nautilus)

**Comment by trappertribiani** [comment]
Nautilus authentication is production ready. Mobile wallet is still in progress, need clarity on ergonode url & how to test locally.

**Comment by trappertribiani** [comment]
Discussions are working locally. Need to add image uploading support, but that's it.

**Comment by trappertribiani** [comment]
Detail page: likes/dislikes, follow/unfollow, comments, and content. Bug with the comments, the current datetime does not store as a default in the API.
